server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myproject2?serverTimezone=UTC&&characterEncoding=utf8

mybatis:
  mapper-locations: mapper/*.xml

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
