spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  servlet:
    multipart:
      location: /tmp
      max-file-size: 20971520
      max-request-size: 20MB
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8



#打印sql语句
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


myproject2:
  testDataPath: /myproject2/TestData
  compile: /myproject2/compile
  run: /myproject2/run
